# Sample configuration file for the mqccred exit
#
# Copy it to $HOME/.mqs/mqccred.ini or set the
# MQCCRED environment variable to point to it.
#
# Use the runmqccred program to protect passwords
# in this file.
#
# Note: This file should be protected from other user
#       access. Remove unecessary permissions.
#
# The Password attribute is plaintext. It is removed
#   and replaced by the OPW attribute to protect it.
#
# The Force=TRUE attribute setting for a queue manager
#   overrides any userid/password supplied explicitly
#   by the application. The default for this attribute
#   is FALSE.
#
# The CLNTCONN channel definition must have the
# SCYEXIT('mqccred(ChlExit)') attribute in order to
# invoke the channel exit that uses this file.

AllQueueManagers:
   Password=passw0rd
   User=user1

QueueManager:
   Name=QMA
   User=user2
   Password=passw0rd2

QueueManager:
   Name=QMB
   User=user3
   Password=passw0rd3
   Force=TRUE
