#*******************************************************************#
#* Module Name: mqat.ini                                           *#
#* Type       : IBM MQ queue manager configuration file            *#
#  Function   : Define the configuration of application activity   *#
#*              trace for a single queue manager.                  *#
#*                                                                 *#
#* <copyright                                                      *#
#*     notice="copyright-lm-source"                                *#
#*     pids="5724-H72"                                             *#
#*     years="2010, 2016"                                          *#
#*     crc="1200916744" >                                          *#
#*                                                                 *#
#*     Licensed Materials - Property of IBM                        *#
#*                                                                 *#
#*     5724-H72                                                    *#
#*                                                                 *#
#*     (C) Copyright IBM Corp. 2010, 2016                          *#
#*                                                                 *#
#* </copyright>                                                    *#
#*                                                                 *#
#*******************************************************************#

# Global settings stanza, default values
AllActivityTrace:
  ActivityInterval=1
  ActivityCount=100
  TraceLevel=MEDIUM
  TraceMessageData=0
  StopOnGetTraceMsg=ON

# Prevent the sample activity trace program from generating data
ApplicationTrace:
  ApplName=amqsact*
  Trace=OFF
